config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'home#top'
  
  get 'signup' => 'users#new'
  
  resources :users
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  namespace :api, { format: 'json' } do
    resources :members
  end

  resources :members

end

app/models/member.rb
class Member < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token
    
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 50}
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    has_many :members
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    # ランダムなトークンを返す
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # 永続的セッションで使用するユーザーをデータベースに記憶する
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # ユーザーログインを破棄する
    def forget
        update_attribute(:remember_digest, nil)
    end
    
end

app/controllers/api/members_controller.rb
module Api
  class MembersController < ApplicationController

    def index
      @member = Member.all
      render json: @member
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
#require 'phantomjs'

class HomeController < ApplicationController
  def top
    if current_user
      @member = Member.where(user_id:current_user.id)
    else
      render :action => "welcome"
    end
  end
  def welcome
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :logged_in_user, only: [:new]

  def new
    @member = Member.new
  end

  def create
    @member = current_user.members.new(member_params)
#    @member.progress = get_progress(@member)
    if @member.save
      redirect_to root_url
    end
  end

  def edit
    @member=Member.find(params[:id])
  end

  def update
    @member=Member.find(params[:id])
    @member.name=params[:name]
    @member.progress=params[:progress]
    @member.url=params[:url]
    @member.achievement=params[:achievement]
    @member.memo=params[:memo]
 #   @member.progress = get_progress(@member)
    if @member.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @member=Member.find(params[:id])
    @member.destroy
    redirect_to root_path
  end

  private
     # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def member_params
      params.require(:member).permit(:name, :progress, :url, :achievement, :memo)
    end
=begin
    def get_progress(member)
    # URLにアクセスするためのライブラリの読み込み
    require 'open-uri'
    # Nokogiriライブラリの読み込み
    require 'nokogiri'
    require 'net/http'
    require 'uri'

    # スクレイピング先のURL
        url = member.url
        charset = nil
        html = open(url) do |f|
          charset = f.charset # 文字種別を取得
          f.read # htmlを読み込んで変数htmlに渡す
        end
        # htmlをパース(解析)してオブジェクトを生成
        doc = Nokogiri::HTML.parse(html, nil, charset)
        byebug
        doc.css("table").each do |node|
          progress+=node.css('.status-icon')[1].value+","
        end
    end
=end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      # Handle a successful save.
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def new
    @user = User.new
  end

  private
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  # ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
# 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/home/top.html.erb
<br>
<%= link_to "追加", new_member_path ,{class: "btn btn-info", :style => "text-align:right;"} %>
<% if current_user %>
    <div class="container">
        <div class="row">
          <table class="table">
            <thead>
              <tr><th>名前</th><th>進捗</th><th>techfile</th><th>到達</th><th>メモ</th><th>編集</th><th>削除</th></tr>
            </thead>
            <tbody>
            <% @member.each do |member| %>
              <tr>
                <td><%= member.name %></td>
                <td><%= member.progress %></td>
                <td><%= link_to member.url, member.url,class:"btn btn-link", role:"button" %></td>
                <td><%= member.achievement %>/9</td>
                <td><%= member.memo %></td>
                <td><%= link_to "編集", edit_member_path(member.id),class:"btn btn-success", role:"button" %></td>
                <td><%= link_to "削除", member_path(member.id), :method => :delete, class:"btn btn-danger", role:"button" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
<% end %>
<script>
</script>

app/views/home/welcome.erb
</div>
<header class="header">
  <div class="text-center logo">
    <h1>Member Progress</h1>
    <h2>メンバーひとりひとりを、ちゃんと見てあげたい</h2>
  </div>
</header>
<section style="height:5px;background:#B8B3BE;">
</section>
<section>
  <div class="container">
    <h2 align="center">Whats?</h2>
    <hr class="small">
    <div class="row">
      <div class="col-sm-3">
        <%= image_tag 'img1.png', :size => "300x300", :class => "img-circle" %>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-7">
        <br>
        <h3>オリジナル作品、誰がどこまで終わってるんだっけ？</h3>
        <p>
          キャンプの終わりが近づくに連れて、発表会へ向けたオリジナル作品の制作が白熱します<br>
          そんな時でも、誰がどこまでやっているかをまとめて見られるように
        </p>
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="col-sm-1">
      </div>
      <div class="col-sm-7">
        <br>
        <h3>開発時間外の話題に困る…</h3>
        <p>
          誰が何をやっているのかを班で共有することにより、メンバーの興味を引き出したり、<br>
          メンバー同士のコミュニケーションが生まれるかもしれません
        </p>
      </div>
      <div class="col-sm-3">
        <%= image_tag 'img2.png', :size => "300x300", :class => "img-circle" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-3">
        <%= image_tag 'img3.png', :size => "300x300", :class => "img-circle" %>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-7">
        <br>
        <h3>全員分のtechfil更新ってちょっと大変…</h3>
        <p>
          メンバー全員のtechfileリンクを一覧表示！
        </p>
      </div>
    </div>
  </div>
</sectoin>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Member Progress", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/members/edit.html.erb
<% provide(:title, 'Add member') %>
<h1>Edit member</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag member_path(@member.id), method: 'patch' do %>

      <%= label_tag :name %>
      <%= text_field_tag :name, @member.name, class: 'form-control' %>

      <%= label_tag :progress %>
      <%= text_field_tag :progress, @member.progress, class: 'form-control' %>

      <%= label_tag :url %>
      <%= text_field_tag :url, @member.url, class: 'form-control' %>

      <%= label_tag :achievement %>
      <%= text_field_tag :achievement, @member.achievement, class: 'form-control' %>

      <%= label_tag :memo %>
      <%= text_field_tag :memo, @member.memo, class: 'form-control' %>

      <%= submit_tag "完了", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/members/new.html.erb
<% provide(:title, 'Add member') %>
<h1>Add member</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :progress %>
      <%= f.text_field :progress, class: 'form-control' %>

      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>

      <%= f.label :achievement %>
      <%= f.text_field :achievement, class: 'form-control' %>

      <%= f.label :memo %>
      <%= f.text_field :memo, class: 'form-control' %>

      <%= f.submit "Add member", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>